---
title: # Tool Links

以下是一些有用的工具和资源链接：

- **序列分析**
  - [BLAST](https://blast.ncbi.nlm.nih.gov/) - 基本局部比对搜索工具
  - [Clustal Omega](https://www.ebi.ac.uk/Tools/msa/clustalo/) - 多序列比对工具
  - [MEGA](https://www.megasoftware.net/) - 分子进化遗传分析软件

- **基因组学**
  - [UCSC Genome Browser](https://genome.ucsc.edu/) - 基因组浏览器
  - [Ensembl](https://www.ensembl.org/) - 基因组注释数据库
  - [IGV](https://software.broadinstitute.org/software/igv/) - 基因组数据可视化工具

- **蛋白质组学**
  - [UniProt](https://www.uniprot.org/) - 蛋白质序列和功能数据库
  - [PDB](https://www.rcsb.org/) - 蛋白质结构数据库
  - [STRING](https://string-db.org/) - 蛋白质-蛋白质相互作用数据库

- **转录组学**
  - [GEO](https://www.ncbi.nlm.nih.gov/geo/) - 基因表达综合数据库
  - [DESeq2](https://bioconductor.org/packages/deSeq2/) - 差异表达分析工具
  - [Seurat](https://satijalab.org/seurat/) - 单细胞RNA测序分析工具

- **其他资源**
  - [NCBI](https://www.ncbi.nlm.nih.gov/) - 国家生物技术信息中心
  - [BioStars](https://www.biostars.org/) - 生物信息学问答社区
  - [OMIM](https://www.omim.org/) - 在线人类孟德尔遗传数据库

- **分析平台**
  - [Galaxy](https://usegalaxy.org/) - 生物信息学分析平台
  - [GenePattern](https://genepattern.org/) - 基因组学分析平台
  - [Cytoscape](https://cytoscape.org/) - 网络可视化和分析平台

- **数据库**
  - [KEGG](https://www.kegg.jp/) - 京都基因与基因组百科全书
  - [Reactome](https://reactome.org/) - 生物通路数据库
  - [GO](http://geneontology.org/) - 基因本体论数据库

- **编程资源**
  - [Bioconductor](https://bioconductor.org/) - R语言生物信息学软件包
  - [Biopython](https://biopython.org/) - Python生物信息学工具包
  - [BioPerl](https://bioperl.org/) - Perl生物信息学工具包

- **学习资源**
  - [Coursera Bioinformatics](https://www.coursera.org/learn/bioinformatics) - 生物信息学在线课程
  - [Rosalind](http://rosalind.info/) - 生物信息学编程练习平台
  - [ExPASy](https://www.expasy.org/) - 生物信息学资源门户网站

- **可视化工具**
  - [RStudio](https://www.rstudio.com/) - R语言集成开发环境
  - [Jupyter Notebook](https://jupyter.org/) - 交互式计算环境
  - [Tableau](https://www.tableau.com/) - 数据可视化工具

- **云计算平台**
  - [AWS Bioinformatics](https://aws.amazon.com/bioinformatics/) - 亚马逊云生物信息学服务
  - [Google Cloud Life Sciences](https://cloud.google.com/life-sciences) - 谷歌云生命科学平台
  - [Microsoft Azure Bioinformatics](https://azure.microsoft.com/en-us/solutions/bioinformatics/) - 微软Azure生物信息学服务

- **期刊和出版物**
  - [Nature Biotechnology](https://www.nature.com/nbt/) - 自然生物技术
  - [Bioinformatics](https://academic.oup.com/bioinformatics) - 生物信息学期刊
  - [Genome Biology](https://genomebiology.biomedcentral.com/) - 基因组生物学

- **会议和研讨会**
  - [ISMB](https://www.iscb.org/ismb) - 国际分子系统生物学会议
  - [PSB](https://psb.stanford.edu/) - Pacific Symposium on Biocomputing
  - [BIBM](https://www.bibm.org/) - 生物医学与生物信息学国际会议

- **社区和论坛**
  - [Bioinformatics Stack Exchange](https://bioinformatics.stackexchange.com/) - 生物信息学问答平台
  - [SEQanswers](http://seqanswers.com/) - 测序技术论坛
  - [GitHub Bioinformatics](https://github.com/bioinformatics) - GitHub生物信息学资源

- **软件工具**
  - [SAMtools](https://www.htslib.org/) - 序列比对/映射工具
  - [BCFtools](https://www.htslib.org/) - VCF文件处理工具
  - [bedtools](https://bedtools.readthedocs.io/) - 基因组区间操作工具

- **在线课程**
  - [edX Bioinformatics](https://www.edx.org/learn/bioinformatics) - edX生物信息学课程
  - [Udemy Bioinformatics](https://www.udemy.com/topic/bioinformatics/) - Udemy生物信息学课程
  - [Khan Academy](https://www.khanacademy.org/science/biology) - 可汗学院生物学课程

- **博客和教程**
  - [Bioinformatics Blueprint](https://bioinformaticsblueprint.com/) - 生物信息学蓝图
  - [The Biostar Handbook](https://www.biostarhandbook.com/) - 生物信息学手册
  - [Ten Simple Rules](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1003773) - 十条简单规则系列文章

- **数据集和基准测试**
  - [ENCODE](https://www.encodeproject.org/) - DNA元件百科全书
  - [GTEx](https://www.gtexportal.org/) - 基因型-组织表达项目
  - [TCGA](https://www.cancer.gov/tcga) - 癌症基因组图谱

- **标准和协议**
  - [FASTA format](https://en.wikipedia.org/wiki/FASTA_format) - FASTA格式
  - [FASTQ format](https://en.wikipedia.org/wiki/FASTQ_format) - FASTQ格式
  - [SAM/BAM format](https://samtools.github.io/hts-specs/SAMv1.pdf) - SAM/BAM格式规范

- **生物信息学软件包**
  - [Bioconductor packages](https://bioconductor.org/packages/release/BiocViews.html#___Software) - Bioconductor软件包
  - [CRAN Task Views: Biostatistics](https://cran.r-project.org/web/views/Biostatistics.html) - CRAN生物统计学任务视图
  - [Python科学计算栈](https://scipy.org/) - SciPy, NumPy, Pandas等

- **基因组浏览器**
  - [UCSC Genome Browser](https://genome.ucsc.edu/) - UCSC基因组浏览器
  - [Ensembl Genome Browser](https://www.ensembl.org) - Ensembl基因组浏览器
  - [IGV](https://software.broadinstitute.org/software/igv/) - Integrative Genomics Viewer

- **变异注释工具**
  - [ANNOVAR](https://annovar.openbioinformatics.org/) - 变异注释工具
  - [VEP](https://www.ensembl.org/Tools/VEP) - 变异效应预测器
  - [SnpEff](https://snpeff.sourceforge.net/) - 基因组变异效应预测工具

- **质量控制工具**
  - [FastQC](https://www.bioinformatics.babraham.ac.uk/projects/fastqc/) - FASTQ文件质量控制
  - [MultiQC](https://multiqc.info/) - 多文件质量控制汇总
  - [Qualimap](http://qualimap.bioinfo.cipf.es/) - 高通量测序数据质量评估

- **变异调用工具**
  - [GATK](https://software.broadinstitute.org/gatk/) - 基因组分析工具包
  - [FreeBayes](https://github.com/ekg/freebayes) - 贝叶斯变异调用工具
  - [VarScan](https://varscan.sourceforge.net/) - 变异检测工具

- **RNA-seq分析工具**
  - [HISAT2](https://ccb.jhu.edu/software/hisat2/index.shtml) - RNA-seq比对工具
  - [STAR](https://github.com/alexdobin/STAR) - RNA-seq比对工具
  - [featureCounts](http://subread.sourceforge.net/) - 基因表达定量工具

- **单细胞分析工具**
  - [Cell Ranger](https://www.10xgenomics.com/products/cell-ranger) - 10x Genomics单细胞分析工具
  - [Scanpy](https://scanpy.readthedocs.io/) - Python单细胞分析工具
  - [Monocle](https://cole-trapnell-lab.github.io/monocle3/) - 单细胞轨迹分析工具

- **ChIP-seq分析工具**
  - [MACS2](https://github.com/taoliu/MACS) - ChIP-seq峰值检测工具
  - [HOMER](http://homer.ucsd.edu/homer/) - ChIP-seq分析工具
  - [deepTools](https://deeptools.readthedocs.io/) - ChIP-seq数据可视化和分析工具

- **宏基因组学工具**
  - [MetaPhlAn](https://www.bioinformatics.babraham.ac.uk/projects/metaphlan/) - 微生物组成分析工具
  - [Kraken](https://ccb.jhu.edu/software/kraken/) - 宏基因组分类工具
  - [QIIME2](https://qiime2.org/) - 微生物组分析平台

- **结构生物学工具**
  - [PyMOL](https://pymol.org/) - 分子可视化软件
  - [Rosetta](https://www.rosettacommons.org/) - 蛋白质结构预测和设计
  - [AlphaFold](https://alphafold.ebi.ac.uk/) - 蛋白质结构预测工具

- **药物发现工具**
  - [AutoDock](https://autodock.scripps.edu/) - 分子对接工具
  - [Schrödinger](https://www.schrodinger.com/) - 药物发现平台
  - [RDKit](https://www.rdkit.org/) - 化学信息学工具包

- **临床基因组学工具**
  - [ClinVar](https://www.ncbi.nlm.nih.gov/clinvar/) - 临床变异数据库
  - [COSMIC](https://cancer.sanger.ac.uk/cosmic) - 体细胞突变目录
  - [OncoKB](https://www.oncokb.org/) - 癌症基因组知识库

- **生物信息学数据库**
  - [GenBank](https://www.ncbi.nlm.nih.gov/genbank/) - 核酸序列数据库
  - [RefSeq](https://www.ncbi.nlm.nih.gov/refseq/) - 参考序列数据库
  - [SRA](https://www.ncbi.nlm.nih.gov/sra) - 序列读段存档

- **基因组注释工具**
  - [Prokka](https://github.com/tseemann/prokka) - 原核基因组注释工具
  - [RAST](https://rast.nmpdr.org/) - 基因组快速注释系统
  - [MAKER](https://www.yandell-lab.org/software/maker.html) - 基因组注释系统

- **代谢组学工具**
  - [XCMS](https://bioconductor.org/packages/xcms/) - LC-MS数据处理工具
  - [MetaboAnalyst](https://www.metaboanalyst.ca/) - 代谢组学分析平台
  - [MS-DIAL](https://prime.psc.riken.jp/compms/msdial/main.html) - 代谢组学数据分析工具

- **网络分析工具**
  - [Cytoscape](https://cytoscape.org/) - 网络可视化和分析平台
  - [Gephi](https://gephi.org/) - 网络可视化工具
  - [NetworkX](https://networkx.org/) - Python网络分析库

- **机器学习工具**
  - [scikit-learn](https://scikit-learn.org/) - Python机器学习库
  - [TensorFlow](https://www.tensorflow.org/) - 深度学习框架
  - [PyTorch](https://pytorch.org/) - 深度学习框架

- **版本控制和协作**
  - [GitHub](https://github.com/) - 代码托管平台
  - [GitLab](https://gitlab.com/) - 代码托管和CI/CD平台
  - [Bitbucket](https://bitbucket.org/) - 代码托管平台

- **容器化技术**
  - [Docker](https://www.docker.com/) - 容器化平台
  - [Singularity](https://sylabs.io/singularity/) - 容器化平台（主要用于HPC）
  - [Biocontainers](https://biocontainers.pro/) - 生物信息学容器镜像

- **工作流管理系统**
  - [Nextflow](https://www.nextflow.io/) - 工作流管理系统
  - [Snakemake](https://snakemake.readthedocs.io/) - 工作流管理系统
  - [Cromwell](https://github.com/broadinstitute/cromwell) - 工作流管理系统

- **云计算资源**
  - [Terra](https://terra.bio/) - 云端生物医学研究平台
  - [DNAnexus](https://www.dnanexus.com/) - 基因组数据分析平台
  - [Seven Bridges](https://www.sevenbridges.com/) - 生物信息学分析平台

- **可视化和报告**
  - [R Markdown](https://rmarkdown.rstudio.com/) - R语言动态文档生成
  - [Jupyter Notebook](https://jupyter.org/) - 交互式计算环境
  - [Quarto](https://quarto.org/) - 科学和技术文档发布系统

- **性能优化工具**
  - [GNU Parallel](https://www.gnu.org/software/parallel/) - 并行计算工具
  - [htop](https://htop.dev/) - 进程监控工具
  - [I/O Meter](https://www.iometer.org/) - I/O性能测试工具

- **调试和测试工具**
  - [GDB](https://www.gnu.org/software/gdb/) - GNU调试器
  - [Valgrind](https://valgrind.org/) - 内存调试和分析工具
  - [pytest](https://docs.pytest.org/) - Python测试框架

- **文档和帮助资源**
  - [Stack Overflow](https://stackoverflow.com/) - 编程问答社区
  - [GitHub Discussions](https://github.com/topics/discussions) - GitHub讨论区
  - [Biostar](https://www.biostars.org/) - 生物信息学问答社区

- **学术资源**
  - [PubMed](https://pubmed.ncbi.nlm.nih.gov/) - 生物医学文献数据库
  - [Google Scholar](https://scholar.google.com/) - 学术搜索引擎
  - [arXiv](https://arxiv.org/) - 预印本服务器

- **培训和认证**
  - [Coursera](https://www.coursera.org/) - 在线课程平台
  - [edX](https://www.edx.org/) - 在线课程平台
  - [DataCamp](https://www.datacamp.com/) - 数据科学在线课程

- **开源项目**
  - [Bioconductor](https://bioconductor.org/) - R语言生物信息学软件包
  - [Galaxy Project](https://galaxyproject.org/) - 生物信息学平台
  - [OpenBio](https://openbio.org/) - 开源生物信息学

- **行业新闻和博客**
  - [GenomeWeb](https://www.genomeweb.com/) - 基因组学新闻
  - [Bio-IT World](https://www.bio-itworld.com/) - 生物IT世界
  - [The Official Blog](https://www.illumina.com/company/news-blog.html) - Illumina官方博客

- **会议和研讨会**
  - [ISMB](https://www.iscb.org/ismb) - 国际分子系统生物学会议
  - [PSB](https://psb.stanford.edu/) - Pacific Symposium on Biocomputing
  - [BIBM](https://www.bibm.org/) - 生物医学与生物信息学国际会议

- **社区和论坛**
  - [Bioinformatics Stack Exchange](https://bioinformatics.stackexchange.com/) - 生物信息学问答平台
  - [SEQanswers](http://seqanswers.com/) - 测序技术论坛
  - [GitHub Bioinformatics](https://github.com/bioinformatics) - GitHub生物信息学资源

- **软件工具**
  - [SAMtools](https://www.htslib.org/) - 序列比对/映射工具
  - [BCFtools](https://www.htslib.org/) - VCF文件处理工具
  - [bedtools](https://bedtools.readthedocs.io/) - 基因组区间操作
---

## 其他可视化工具

```{r}
#| echo: false

library(pixture)

paths <- c(
  "https://raw.githubusercontent.com/openbiox/Bizard/refs/heads/main/images/ToolLinks/ggalign.png",
  "https://raw.githubusercontent.com/openbiox/Bizard/refs/heads/main/images/ToolLinks/FigureYa.png",
  "https://raw.githubusercontent.com/openbiox/Bizard/refs/heads/main/images/ToolLinks/Awesome-genome-vis.png",
  "https://raw.githubusercontent.com/openbiox/Bizard/refs/heads/main/images/ToolLinks/Marsilea.png",
  "https://raw.githubusercontent.com/openbiox/Bizard/refs/heads/main/images/ToolLinks/tidyplots.png",
  "https://raw.githubusercontent.com/openbiox/Bizard/refs/heads/main/images/ToolLinks/ggrecipes.png",
  "https://raw.githubusercontent.com/openbiox/Bizard/refs/heads/main/images/ToolLinks/scidraw.png"
)

title <- c(
  "ggalign-gallery",
  "FigureYa",
  "awesome-genome-visualization",
  "Marsilea",
  "tidyplots",
  "ggrecipes",
  "scidraw"
)

describe <- c(
  "Integrative Composable Visualization",
  "317 Visualization Code Framework",
  "A list of genome visualization programs",
  "Declarative creation of composable visualization",
  "Tidy plots for scientific publications",
  "Recipes for ggplot2 visualizations",
  "Scientific drawing and illustration tool"
)

link <- c(
  "https://yunuuuu.github.io/ggalign-gallery/",
  "https://ying-ge.github.io/FigureYa/",
  "https://cmdcolin.github.io/awesome-genome-visualization/",
  "https://marsilea.rtfd.io/",
  "https://jbengler.github.io/tidyplots/",
  "https://ignophi.github.io/ggrecipes/index.html",
  "https://scidraw.msttnote.cn/"
)

captions <- paste0(
  "<div style='line-height:0.1;'>",
  paste0("<div style='font-size:1.0rem;margin-bottom:0.2em;line-height:1;color:#34495e;'><b>", title, "</b></div>"),
  paste0("<div style='line-height:1.2;font-size:0.7rem;color:#808b96;'>", describe, "</div>"),
  "</div>"
)

pixgallery(
  path = paths,
  caption = captions,
  caption_valign = "below",
  caption_halign = "center",
  link = link,
  h = "250px",
  w = "250px", 
  border_radius = "10px",
  gap = "10px",
  layout = "fixed"
)
```

## Web 可视化应用

```{r}
#| echo: false

paths <- c(
  "https://raw.githubusercontent.com/openbiox/Bizard/refs/heads/main/images/ToolLinks/Hiplot.png",
  "https://raw.githubusercontent.com/openbiox/Bizard/refs/heads/main/images/ToolLinks/UCSCXenaShiny.png",
  "https://raw.githubusercontent.com/openbiox/Bizard/refs/heads/main/images/ToolLinks/CNScolor.png"
)

title <- c(
  "Hiplot",
  "UCSCXenaShiny",
  "CNScolor"
)

describe <- c(
  "Biomedical Data Visualization",
  "UCSCXenaShiny Hub Shiny App",
  "Open source CNS color website"
)

link <- c(
  "https://hiplot.cn/",
  "https://shiny.zhoulab.ac.cn/UCSCXenaShiny/",
  "https://tigerz.shinyapps.io/CNScolor/"
)

captions <- paste0(
  "<div style='line-height:0.1;'>",
  paste0("<div style='font-size:1.0rem;margin-bottom:0.2em;line-height:1;color:#34495e;'><b>", title, "</b></div>"),
  paste0("<div style='line-height:1.2;font-size:0.7rem;color:#808b96;'>", describe, "</div>"),
  "</div>"
)

pixgallery(
  path = paths,
  caption = captions,
  caption_valign = "below",
  caption_halign = "center",
  link = link,
  h = "250px",
  w = "250px", 
  border_radius = "10px",
  gap = "10px",
  layout = "fixed"
)
```