---
title: "面积图"
author:
  - "**[编辑]** 郑虎;"
  - "**[审核]** ."
---

面积图是一种基于折线图并以图形方式显示定量数据的图形。轴和线之间的区域通常用颜色、纹理和图案来强调。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `ggplot2`; `ggthemes`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}
if (!requireNamespace("ggthemes", quietly = TRUE)) {
  install.packages("ggthemes")
}

# 加载包
library(ggplot2)
library(ggthemes)
```

## 数据准备

载入数据为 x 轴数值和 y 轴数值。

```{r load data, message=FALSE}
# 加载数据
data <- read.table("files/Hiplot/001-area-data.txt", header = T)
# 查看数据
head(data)
```

## 可视化

```{r fig-1Area}
#| label: fig-1Area
#| fig-cap: "面积图"
#| out.width: "95%"
#| warning: false

# 面积图
p <- ggplot(data, aes(x = xaxis.value, y = yaxis.value, fill = group)) +
  geom_area(alpha = 1) +
  ylab("yaxis.value") +
  xlab("xaxis.value") +
  ggtitle("Area Plot") +
  scale_fill_manual(values = c("#e04d39","#5bbad6","#1e9f86")) +
  theme_stata() +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12,hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 0, hjust = 0.5,vjust = 1),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))

p
```

不同颜色代表不同组的面积图。

