---
title: "颜色组柱状图"
author:
  - "**[编辑]** 郑虎;"
  - "**[审核]** ."
---

颜色组柱状图可以用于分组展示数据值，并按顺序标注不同颜色。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `plot3D`; `ggplotify`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("plot3D", quietly = TRUE)) {
  install.packages("plot3D")
}
if (!requireNamespace("ggplotify", quietly = TRUE)) {
  install.packages("ggplotify")
}

# 加载包
library(ggplot2)
library(stringr)
```

## 数据准备

数据表格（三列）：

Term | 条目名称，如 GO/KEGG 通路名称

Count | 条目的数值大小，如某通路富集到的基因数

Type | 该通路所属大类：如 BP/MF/CC/KEGG

```{r load data, message=FALSE}
# 加载数据
data <- read.delim("files/Hiplot/004-barplot-color-group-data.txt", header = T)

# 整理数据格式
colnames(data) <- c("term", "count", "type")
data[,"term"] <- str_to_sentence(str_remove(data[,"term"], pattern = "\\w+:\\d+\\W"))
data[,"term"] <- factor(data[,"term"], 
                        levels =  data[,"term"][length(data[,"term"]):1])
data[,"type"] <- factor(data[,"type"], 
                        levels = data[!duplicated(data[,"type"]), "type"])

# 查看数据
data
```

## 可视化

```{r fig-1barplot-color-group}
#| label: fig-1barplot-color-group
#| fig-cap: "颜色组柱状图"
#| out.width: "95%"
#| warning: false

# 三维柱状图
p <- ggplot(data = data, aes(x = term, y = count, fill = type)) +
  geom_bar(stat = "identity", width = 0.8) + 
  theme_bw() +
  xlab("Count") +
  ylab("Term") +
  guides(fill = guide_legend(title="Type")) +
  ggtitle("Barplot Color Group") + 
  coord_flip() +
  theme_classic() +
  scale_fill_manual(values = c("#E64B35FF","#4DBBD5FF","#00A087FF","#3C5488FF")) +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12,hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 0, hjust = 0.5,vjust = 1),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))

p
```

上图展示了 GO/KEGG 通路富集分析结果的可视化。



