---
title: "Beanplot"
author:
  - "**[Editor]** Hu Zheng;"
  - "**[Contributors]** "
---

The beanplot is a method of visualizing the distribution characteristics.

## Setup

-   System Requirements: Cross-platform (Linux/MacOS/Windows)

-   Programming language: R

-   Dependent packages: `ggplotify`; `beanplot`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# Install packages
if (!requireNamespace("ggplotify", quietly = TRUE)) {
  install.packages("ggplotify")
}
if (!requireNamespace("beanplot", quietly = TRUE)) {
  install.packages("beanplot")
}

# Load packages
library(ggplotify)
library(beanplot)
```

## Data Preparation

The loaded data is data set (data on treatment outcomes of different treatment regimens).

```{r load data, message=FALSE}
# Load data
data <- read.table("files/Hiplot/011-beanplot-data.txt", header = T)

# convert data structure
GroupOrder <- as.numeric(factor(data[, 2], levels = unique(data[, 2])))
data[, 2] <- paste0(data[,2], " ", as.numeric(factor(data[, 3])))
data <- cbind(data, GroupOrder)

# View data
head(data)
```

## Visualization

```{r fig-1Beanplot}
#| label: fig-1Beanplot
#| fig-cap: "Beanplot"
#| out.width: "95%"
#| warning: false

# Beanplot
p <- as.ggplot(function() {
  beanplot(Y ~ reorder(X, GroupOrder, mean), data = data, ll = 0.04,
           main = "Bean Plot", ylab = "Y", xlab = "X", side = "both",
           border = NA, horizontal = F, 
           col = list(c("#2b70c4", "#2b70c4"),c("#e9c216", "#e9c216")),
           beanlines = "mean", overallline = "mean", kernel = "gaussian")
  
  legend("bottomright", fill = c("#2b70c4", "#e9c216"),
         legend = levels(factor(data[, 3])))
})

p
```

