---
title: "Bivariate Chart"
author:
  - "**[Editor]** Hu Zheng;"
  - "**[Contributors]** "
---

Display the bivariate.

## Setup

-   System Requirements: Cross-platform (Linux/MacOS/Windows)

-   Programming language: R

-   Dependent packages: `GGally`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# Install packages
if (!requireNamespace("GGally", quietly = TRUE)) {
  install.packages("GGally")
}

# Load packages
library(GGally)
```

## Data Preparation

```{r load data, message=FALSE}
# Load data
data <- read.table("files/Hiplot/014-bivariate-data.txt", header = T)

# View data
head(data)
```

## Visualization

```{r fig-1Bivariate}
#| label: fig-1Bivariate
#| fig-cap: "Bivariate Chart"
#| out.width: "95%"
#| warning: false

# Bivariate Chart
p <- ggbivariate(data, outcome = "smoker", 
                 explanatory = c("day","time","gender","tip")) +
  ggtitle("Bivariate") +
  scale_fill_manual(values = c("#e04d39","#5bbad6")) +
  theme_bw() +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12,hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 0, hjust = 0.5),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))

p
```


