---
title: "双变量图"
author:
  - "**[编辑]** 郑虎;"
  - "**[审核]** ."
---

展示双变量关系。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `GGally`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("GGally", quietly = TRUE)) {
  install.packages("GGally")
}

# 加载包
library(data.table)
library(jsonlite)
library(GGally)
```

## 数据准备

```{r load data, message=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/bivariate/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# 查看数据
head(data)
```

## 可视化

```{r fig-1Bivariate}
#| label: fig-1Bivariate
#| fig-cap: "双变量图"
#| out.width: "95%"
#| fig-height: 5
#| fig-width: 8
#| warning: false

# 双变量图
p <- ggbivariate(data, outcome = "smoker", 
                 explanatory = c("day","time","gender","tip")) +
  ggtitle("Bivariate") +
  scale_fill_manual(values = c("#e04d39","#5bbad6")) +
  theme_bw() +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12,hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 0, hjust = 0.5),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))

p
```





