---
title: Bumpchart
author:
  - "**[Editor]** [Hu Zheng](https://github.com/ZhengTiger);"
  - "**[Contributors]** "
---

::: callout-note
**Hiplot 网站**

此页面是 Hiplot `Bumpchart` 插件源代码版本的教程。您也可以使用 Hiplot 网站实现无代码绘图。更多信息请参见以下链接：

<https://hiplot.cn/basic/bumpchart?lang=en>
:::

升降图（Bump chart）可用于显示分组数值的变化。

## 设置

-   系统要求：跨平台（Linux/MacOS/Windows）

-   编程语言：R

-   依赖包：`data.table`；`jsonlite`；`ggplot2`；`ggbump`；`dplyr`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# Install packages
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}
if (!requireNamespace("ggbump", quietly = TRUE)) {
  install.packages("https://cran.r-project.org/src/contrib/Archive/ggbump/ggbump_0.1.0.tar.gz")
}
if (!requireNamespace("dplyr", quietly = TRUE)) {
  install.packages("dplyr")
}

# Load packages
library(data.table)
library(jsonlite)
library(ggplot2)
library(ggbump)
library(dplyr)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

```{r load data, message=FALSE}
# Load data
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/bumpchart/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# View data
head(data)
```

## 可视化

```{r fig-1Bumpchart}
#| label: fig-1Bumpchart
#| fig-cap: "Bumpchart"
#| out.width: "95%"
#| fig-height: 4
#| fig-width: 6
#| warning: false

# Bumpchart
p <- ggplot(data, aes(x = x, y = y, color = group)) +
  geom_bump(size = 1.5) +
  geom_point(size = 5) +
  geom_text(data = data %>% filter(x == min(x)),
            aes(x = x - 0.1, label = group),
            size = 5, hjust = 1) +
  geom_text(data = data %>% filter(x == max(x)),
            aes(x = x + 0.1, label = group),
            size = 5, hjust = 0) +
  theme_void() +
  theme(legend.position = "none") +
  scale_color_manual(values = c("#0571B0","#92C5DE","#F4A582","#CA0020"))

p
```