---
title: "Bumpchart"
author:
  - "**[Editor]** Hu Zheng;"
  - "**[Contributors]** "
---

Bump chart can be used to display the change of grouped values.

## Setup

-   System Requirements: Cross-platform (Linux/MacOS/Windows)

-   Programming language: R

-   Dependent packages: `ggplot2`; `ggbump`; `dplyr`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# Install packages
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}
if (!requireNamespace("ggbump", quietly = TRUE)) {
  install.packages("ggbump")
}
if (!requireNamespace("dplyr", quietly = TRUE)) {
  install.packages("dplyr")
}

# Load packages
library(ggplot2)
library(ggbump)
library(dplyr)
```

## Data Preparation

```{r load data, message=FALSE}
# Load data
data <- read.table("files/Hiplot/017-bumpchart-data.txt", header = T)

# View data
head(data)
```

## Visualization

```{r fig-1Bumpchart}
#| label: fig-1Bumpchart
#| fig-cap: "Bumpchart"
#| out.width: "95%"
#| warning: false

# Bumpchart
p <- ggplot(data, aes(x = x, y = y, color = group)) +
  geom_bump(size = 1.5) +
  geom_point(size = 5) +
  geom_text(data = data %>% filter(x == min(x)),
            aes(x = x - 0.1, label = group),
            size = 5, hjust = 1) +
  geom_text(data = data %>% filter(x == max(x)),
            aes(x = x + 0.1, label = group),
            size = 5, hjust = 0) +
  theme_void() +
  theme(legend.position = "none") +
  scale_color_manual(values = c("#0571B0","#92C5DE","#F4A582","#CA0020"))

p
```



