---
title: "简单可变相关热图"
author:
  - "**[编辑]** 郑虎;"
  - "**[审核]** ."
---

提供一个简单化版本的相关热图可视化。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `ggplot2`; `sigminer`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}
if (!requireNamespace("sigminer", quietly = TRUE)) {
  install.packages("sigminer")
}

# 加载包
library(ggplot2)
library(sigminer)
```

## 数据准备

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- read.delim("files/Hiplot/029-cor-heatmap-simple-data.txt", header = T)

# 查看数据
head(data)
```

## 可视化

```{r fig-1Cor-heatmap-simple}
#| label: fig-1Cor-heatmap-simple
#| fig-cap: "简单可变相关热图"
#| out.width: "95%"
#| fig-height: 6
#| fig-width: 6
#| warning: false
#| message: false

# 简单可变相关热图
p <- show_cor(
  data = data,
  x_vars = c("mpg","cyl","disp"),
  y_vars = c("wt","hp","drat"),
  cor_method = "pearson",
  vis_method = "square",
  lab = T,
  test = T,
  hc_order = F,
  legend.title = "Corr"
  ) +
  ggtitle("") +
  labs(x="", y="") +
  theme_bw() +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12,hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))

p
```

