---
title: "自定义热图"
author:
  - "**[编辑]** 郑虎;"
  - "**[审核]** ."
---

自定义热图，按照给定数据直接绘制热图。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `ggplot2`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}

# 加载包
library(ggplot2)
```

## 数据准备

案例数据为hiplot.org官方logo的灰度图像。

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- read.delim("files/Hiplot/034-custom-heat-map-data.txt", header = T)

# 整理数据格式
draw_data <- as.matrix(data[, 2:ncol(data)])
row_num <- nrow(draw_data)
col_num <- ncol(draw_data)
col_labels <- colnames(data)
col_labels <- col_labels[2:ncol(data)]
row_labels <- data$name
rm(data)
df <- expand.grid(row = 1:row_num, col = 1:col_num)
df$value <- c(draw_data)

# 查看数据
head(df)
```

## 可视化

```{r fig-1Custom-heat-map}
#| label: fig-1Custom-heat-map
#| fig-cap: "自定义热图"
#| out.width: "95%"
#| fig-height: 15
#| fig-width: 25
#| warning: false
#| message: false

# 自定义热图
p <- ggplot(df, aes(x = col, y = row, fill = value)) +
  geom_point(shape = 21, size = 8, aes(fill = value), color = "white") +
  scale_fill_gradient(low = "#DDDDDD", high = "#0000F5") +
  guides(fill = guide_colorbar(title = "Value")) +
  theme(
    panel.background = element_rect(fill = "white"),
    panel.grid = element_blank(),
    axis.text = element_text(size = 10),
    axis.ticks = element_blank(),
    axis.title = element_blank()
    ) +
  scale_x_continuous(breaks = 1:col_num, labels = col_labels, position = "top") +
  scale_y_reverse(breaks = 1:row_num, labels = row_labels, position = "left")

p
```


