---
title: "Custom Icon Scatter"
author:
  - "**[Editor]** Hu Zheng;"
  - "**[Contributors]** "
---

A scatter plot with customizable icons.

## Setup

-   System Requirements: Cross-platform (Linux/MacOS/Windows)

-   Programming language: R

-   Dependent packages: `echarts4r`; `echarts4r.assets`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# Install packages
if (!requireNamespace("echarts4r", quietly = TRUE)) {
  install.packages("echarts4r")
}
if (!requireNamespace("echarts4r.assets", quietly = TRUE)) {
  install_github("JohnCoene/echarts4r.assets")
}

# Load packages
library(echarts4r)
library(echarts4r.assets)
```

## Data Preparation

```{r load data, message=FALSE, warning=FALSE}
# Load data
data <- read.delim("files/Hiplot/035-custom-icon-scatter-data.txt", header = T)

# convert data structure
draw_data <- data.frame(
  x = data[["mpg"]],
  y = data[["wt"]],
  size = data[["qsec"]]
  )
rm(data)

# View data
head(draw_data)
```

## Visualization

```{r fig-1Custom-icon-scatter}
#| label: fig-1Custom-icon-scatter
#| fig-cap: "Custom Icon Scatter"
#| out.width: "95%"
#| warning: false
#| message: false

# Custom Icon Scatter
p <- draw_data |>
  e_charts(x) |>
  e_scatter(
    y,
    size,
    symbol = ea_icons("warning"),
    name = "warning"
    )

p
```

