---
title: "自定义图标散点图"
author:
  - "**[编辑]** 郑虎;"
  - "**[审核]** ."
---

可自定义图标的散点图。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `data.table`; `jsonlite`; `echarts4r`; `echarts4r.assets`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("data.table", quietly = TRUE)) {
  install.packages("data.table")
}
if (!requireNamespace("jsonlite", quietly = TRUE)) {
  install.packages("jsonlite")
}
if (!requireNamespace("echarts4r", quietly = TRUE)) {
  install.packages("echarts4r")
}
if (!requireNamespace("echarts4r.assets", quietly = TRUE)) {
  install_github("JohnCoene/echarts4r.assets")
}

# 加载包
library(data.table)
library(jsonlite)
library(echarts4r)
library(echarts4r.assets)
```

## 数据准备

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- data.table::fread(jsonlite::read_json("https://hiplot.cn/ui/basic/custom-icon-scatter/data.json")$exampleData$textarea[[1]])
data <- as.data.frame(data)

# 整理数据格式
draw_data <- data.frame(
  x = data[["mpg"]],
  y = data[["wt"]],
  size = data[["qsec"]]
  )
rm(data)

# 查看数据
head(draw_data)
```

## 可视化

```{r fig-1Custom-icon-scatter}
#| label: fig-1Custom-icon-scatter
#| fig-cap: "自定义图标散点图"
#| out.width: "95%"
#| warning: false
#| message: false

# 自定义图标散点图
p <- draw_data |>
  e_charts(x) |>
  e_scatter(
    y,
    size,
    symbol = ea_icons("warning"),
    name = "warning"
    )

p
```

