---
title: "D3 Wordcloud"
author:
  - "**[Editor]** Hu Zheng;"
  - "**[Contributors]** "
---

Display the wordcloud。

## Setup

-   System Requirements: Cross-platform (Linux/MacOS/Windows)

-   Programming language: R

-   Dependent packages: `d3wordcloud`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# Install packages
if (!requireNamespace("d3wordcloud", quietly = TRUE)) {
  devtools::install_github("jbkunst/d3wordcloud")
}

# Load packages
library(d3wordcloud)
```

## Data Preparation

```{r load data, message=FALSE, warning=FALSE}
# Load data
data <- read.delim("files/Hiplot/036-d3-wordcloud-data.txt", header = T)

# convert data structure
row.names(data) <- data[, 1]

# View data
head(data)
```

## Visualization

```{r fig-1D3-wordcloud}
#| label: fig-1D3-wordcloud
#| fig-cap: "D3 Wordcloud"
#| out.width: "95%"
#| warning: false
#| message: false

# D3 Wordcloud
p <- d3wordcloud(
  words = data[, 1], 
  freqs = data[, 2],
  padding = 0,
  rotate.min = 0,
  rotate.max = 0,
  size.scale = "linear",
  color.scale = "linear",
  spiral = "archimedean",
  font = "Arial",
  rangesizefont = c(10, 90)
)

p
```



