---
title: "系统树图"
author:
  - "**[编辑]** 郑虎;"
  - "**[审核]** ."
---

系统树图是一种以树的形状表示的图。这种图表在不同情景有不同的含义。如：在层次聚类中，说明了相应分析产生的聚类的排列。在生物信息中，它显示基因或样本的聚集，有时在热图的边缘。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `ape`; `ggplotify`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("ape", quietly = TRUE)) {
  install.packages("ape")
}
if (!requireNamespace("ggplotify", quietly = TRUE)) {
  install.packages("ggplotify")
}

# 加载包
library(ape)
library(ggplotify)
```

## 数据准备

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- read.delim("files/Hiplot/037-dendrogram-data.txt", header = T)

# 整理数据格式
data <- data[, -1]

# 查看数据
head(data)
```

## 可视化

```{r fig-1Dendrogram}
#| label: fig-1Dendrogram
#| fig-cap: "D3 词云"
#| out.width: "95%"
#| fig-height: 4
#| fig-width: 6
#| warning: false
#| message: false

# 系统树图
d <- dist(t(data), method = "euclidean")
hc <- hclust(d, method = "complete")
clus <- cutree(hc, 4)

p <- as.ggplot(function() {
  par(mar = c(5, 5, 10, 5), mgp = c(2.5, 1, 0))
  plot(as.phylo(hc),
       type = "phylogram",
       tip.color = c("#00468bff","#ed0000ff","#42b540ff","#0099b4ff")[clus], 
       label.offset = 1,
       cex = 1, font = 2, use.edge.length = T
       )
  title("Dendrogram Plot", line = 1)
  })

p
```


