---
title: "Density-Histogram"
author:
  - "**[Editor]** Hu Zheng;"
  - "**[Contributors]** "
---

Use density plots or histograms to show data distribution.

## Setup

-   System Requirements: Cross-platform (Linux/MacOS/Windows)

-   Programming language: R

-   Dependent packages: `grafify`; `dplyr`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# Install packages
if (!requireNamespace("grafify", quietly = TRUE)) {
  install.packages("grafify")
}
if (!requireNamespace("dplyr", quietly = TRUE)) {
  install.packages("dplyr")
}

# Load packages
library(grafify)
library(dplyr)
```

## Data Preparation

```{r load data, message=FALSE, warning=FALSE}
# Load data
data <- read.delim("files/Hiplot/039-density-histogram-data.txt", header = T)

# convert data structure
y <- "Doubling_time"
group <- "Student"
data[, group] <- factor(data[, group], levels = unique(data[, group]))
data <- data %>% 
  mutate(median = median(get(y), na.rm = TRUE),
         mean = mean(get(y), na.rm = TRUE))

# View data
head(data)
```

## Visualization

### 1. Density Plot

```{r fig-1Density}
#| label: fig-1Density
#| fig-cap: "Density Plot"
#| out.width: "95%"
#| fig-height: 4
#| fig-width: 6
#| warning: false
#| message: false

# Density Plot
p <- plot_density(
  data = data, 
  ycol = get(y), 
  group = get(group),
  linethick = 0.5,
  c_alpha = 0.6) + 
  ggtitle("Density Plot") + 
  geom_vline(aes_string(xintercept = "median"),
        colour = 'black', linetype = 2, size = 0.5) + 
  xlab(y) + 
  ylab("density") + 
  guides(fill = guide_legend(title = group), color = FALSE) +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12,hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 0, hjust = 0.5,vjust = 1),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))

p
```


### 2. Histogram Plot

```{r fig-2Histogram}
#| label: fig-2Histogram
#| fig-cap: "Histogram Plot"
#| out.width: "95%"
#| fig-height: 4
#| fig-width: 6
#| warning: false
#| message: false

# Histogram Plot
p <- plot_histogram(
  data = data, 
  ycol = get(y), 
  group = get(group),
  linethick = 0.5,
  BinSize = 30)  + 
  ggtitle("Histogram Plot") + 
  geom_vline(aes_string(xintercept = "median"),
        colour = 'black', linetype = 2, size = 0.5) + 
  xlab(y) + 
  ylab("density") + 
  guides(fill = guide_legend(title = group), color = FALSE) +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12,hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 0, hjust = 0.5,vjust = 1),
        legend.position = "bottom",
        legend.direction = "horizontal",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))

p
```


