---
title: "Density"
author:
  - "**[Editor]** Hu Zheng;"
  - "**[Contributors]** "
---

The kernel density map is a graph used to observe the distribution of continuous variables.

## Setup

-   System Requirements: Cross-platform (Linux/MacOS/Windows)

-   Programming language: R

-   Dependent packages: `ggplot2`; `ggthemes`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# Install packages
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}
if (!requireNamespace("ggthemes", quietly = TRUE)) {
  install.packages("ggthemes")
}

# Load packages
library(ggplot2)
library(ggthemes)
```

## Data Preparation

```{r load data, message=FALSE, warning=FALSE}
# Load data
data <- read.delim("files/Hiplot/040-density-data.txt", header = T)

# convert data structure
data[,2] <- factor(data[,2], levels = unique(data[,2]))

# View data
head(data)
```

## Visualization

```{r fig-1Density}
#| label: fig-1Density
#| fig-cap: "Density"
#| out.width: "95%"
#| fig-height: 4
#| fig-width: 6
#| warning: false
#| message: false

# Density
data["group_add_by_code"] <- "g1"

p <- ggplot(data, aes_(as.name(colnames(data[1])))) +
  geom_density(col = "white", alpha = 0.85,
               aes_(fill = as.name(colnames(data[2])))) +
  ggtitle("") +
  scale_fill_manual(values = c("#e04d39","#5bbad6")) +
  theme_stata() +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12,hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 0, hjust = 0.5,vjust = 1),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))

p
```


