---
title: "Deviation Plot"
author:
  - "**[Editor]** Hu Zheng;"
  - "**[Contributors]** "
---

Deviation plot provides a visual representation of the differences between data points.

## Setup

-   System Requirements: Cross-platform (Linux/MacOS/Windows)

-   Programming language: R

-   Dependent packages: `ggpubr`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# Install packages
if (!requireNamespace("ggpubr", quietly = TRUE)) {
  install.packages("ggpubr")
}

# Load packages
library(ggpubr)
```

## Data Preparation

```{r load data, message=FALSE, warning=FALSE}
# Load data
data <- read.delim("files/Hiplot/041-deviation-plot-data.txt", header = T)

# convert data structure
data[["z_score"]] <- (data[["mpg"]] - mean(data[["mpg"]])) / sd(data[["mpg"]])
data[["Group"]] <- factor(ifelse(data[["z_score"]] < 0, "low", "high"),
                          levels = c("low", "high")
                          )

# View data
head(data)
```

## Visualization

```{r fig-1Density}
#| label: fig-1Deviation-plot
#| fig-cap: "Deviation Plot"
#| out.width: "95%"
#| fig-height: 5
#| fig-width: 8
#| warning: false
#| message: false

# Deviation Plot
p <- ggbarplot(data,
    x = "name",
    y = "z_score",
    fill = "Group",
    color = "white",
    sort.val = "desc",
    sort.by.groups = FALSE,
    x.text.angle = 90,
    xlab = "name",
    ylab = "mpg",
    rotate = TRUE
  ) +
  scale_fill_manual(values = c("#e04d39","#5bbad6")) +
  theme_bw() +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12,hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 0, hjust = 0.5,vjust = 1),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))

p
```

