---
title: "DIY GSEA"
author:
  - "**[Editor]** Hu Zheng;"
  - "**[Contributors]** "
---

Make your geneset.

## Setup

-   System Requirements: Cross-platform (Linux/MacOS/Windows)

-   Programming language: R

-   Dependent packages: `clusterProfiler`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# Install packages
if (!requireNamespace("clusterProfiler", quietly = TRUE)) {
  install_github("YuLab-SMU/clusterProfiler")
}

# Load packages
library(clusterProfiler)
```

## Data Preparation

```{r load data, message=FALSE, warning=FALSE}
# Load data
data1 <- read.delim("files/Hiplot/044-diy-gsea-data1.txt", header = T)
data2 <- read.delim("files/Hiplot/044-diy-gsea-data2.txt", header = T)

# convert data structure
data1[,2] <- as.numeric(data1[,2])
geneList <- data1[,2]
names(geneList) <- data1[,1]
geneList <- sort(geneList, decreasing = TRUE)
term <- data.frame(term=data2[,1], gene=data2[,2])

# View data
head(term)
```

## Visualization

```{r fig-1Diy-gsea}
#| label: fig-1Diy-gsea
#| fig-cap: "DIY GSEA"
#| out.width: "95%"
#| fig-height: 4
#| fig-width: 7
#| warning: false
#| message: false

# DIY GSEA
y <- clusterProfiler::GSEA(geneList, TERM2GENE = term, pvalueCutoff = 1)
p <- gseaplot(
  y,
  y@result$Description[1],
  color = "#000000",
  by = "runningScore",
  color.line = "#4CAF50",
  color.vline= "#FA5860",
  title = "DIY GSEA Plot",
  )

p
```

