---
title: "双Y轴图"
author:
  - "**[编辑]** 郑虎;"
  - "**[审核]** ."
---

双Y轴图可以将两组数量级较大的数据放在同一个图中进行展示。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `ggplot2`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}

# 加载包
library(ggplot2)
```

## 数据准备

载入数据为分为三列，第一列是x轴的数值，第二列为左侧Y轴的数值，第三列为右侧Y轴的数值。

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- read.delim("files/Hiplot/047-dual-y-axis-data.txt", header = T)

# 查看数据
head(data)
```

## 可视化

```{r fig-1Dual-y-axis}
#| label: fig-1Dual-y-axis
#| fig-cap: "双Y轴图"
#| out.width: "95%"
#| fig-height: 3
#| fig-width: 4
#| warning: false
#| message: false

# 双Y轴图
p <- ggplot(data, aes(x = x)) +
  geom_line(aes(y = data[, 2]), size = 1, color = "#D72C15") +
  geom_line(aes(y = data[, 3] / as.numeric(10)), size = 1, color = "#02657B") +
  scale_y_continuous(
    name = colnames(data)[2],
    sec.axis = sec_axis(~ . * as.numeric(10), name = colnames(data)[3])) +
  ggtitle("Dual Y Axis Chart") + xlab("x") +
  theme_bw() +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12,hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 0, hjust = 0.5,vjust = 1),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))

p
```

案例数据中左侧Y轴比例尺量级在0-100的范围，而右侧Y轴比例尺则在0-1000。

