---
title: "Easy Pairs"
author:
  - "**[Editor]** Hu Zheng;"
  - "**[Contributors]** "
---

Display a matrix of plots for viewing correlation relationship and distributions of multiple variables.

## Setup

-   System Requirements: Cross-platform (Linux/MacOS/Windows)

-   Programming language: R

-   Dependent packages: `GGally`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# Install packages
if (!requireNamespace("GGally", quietly = TRUE)) {
  install.packages("GGally")
}

# Load packages
library(GGally)
```

## Data Preparation

```{r load data, message=FALSE, warning=FALSE}
# Load data
data <- read.delim("files/Hiplot/049-easy-pairs-data.txt", header = T)

# View data
head(data)
```

## Visualization

```{r fig-1Easy-pairs}
#| label: fig-1Easy-pairs
#| fig-cap: "Easy Pairs"
#| out.width: "95%"
#| fig-height: 8
#| fig-width: 8
#| warning: false
#| message: false

# Easy Pairs
p <- ggpairs(data, columns = c("total_bill", "time", "tip"),
             mapping = aes_string(color = "gender")) +
  ggtitle("Easy Pairs") +
  scale_fill_manual(values = c("#3B4992FF","#EE0000FF")) +
  theme_bw() +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12,hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 0, hjust = 0.5,vjust = 1),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))

p
```


