---
title: "简易配对图"
author:
  - "**[编辑]** 郑虎;"
  - "**[审核]** ."
---

显示一个矩阵图，用于查看多个变量的相关关系和数据分布。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `GGally`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("GGally", quietly = TRUE)) {
  install.packages("GGally")
}

# 加载包
library(GGally)
```

## 数据准备

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- read.delim("files/Hiplot/049-easy-pairs-data.txt", header = T)

# 查看数据
head(data)
```

## 可视化

```{r fig-1Easy-pairs}
#| label: fig-1Easy-pairs
#| fig-cap: "简易配对图"
#| out.width: "95%"
#| fig-height: 8
#| fig-width: 8
#| warning: false
#| message: false

# 简易配对图
p <- ggpairs(data, columns = c("total_bill", "time", "tip"),
             mapping = aes_string(color = "gender")) +
  ggtitle("Easy Pairs") +
  scale_fill_manual(values = c("#3B4992FF","#EE0000FF")) +
  theme_bw() +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12,hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 0, hjust = 0.5,vjust = 1),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))

p
```



