---
title: "Eulerr Plot"
author:
  - "**[Editor]** Hu Zheng;"
  - "**[Contributors]** "
---

## Setup

-   System Requirements: Cross-platform (Linux/MacOS/Windows)

-   Programming language: R

-   Dependent packages: `eulerr`; `ggplotify`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# Install packages
if (!requireNamespace("eulerr", quietly = TRUE)) {
  install.packages("eulerr")
}
if (!requireNamespace("ggplotify", quietly = TRUE)) {
  install.packages("ggplotify")
}

# Load packages
library(eulerr)
library(ggplotify)
```

## Data Preparation

```{r load data, message=FALSE, warning=FALSE}
# Load data
data <- read.delim("files/Hiplot/051-eulerr-data.txt", header = T)

# convert data structure
genes <- as.numeric(data[, 2])
names(genes) <- as.character(data[, 1])
euler_set <- euler(genes)
  
# View data
head(data)
```

## Visualization

```{r fig-1Eulerr}
#| label: fig-1Eulerr
#| fig-cap: "Eulerr Plot"
#| out.width: "95%"
#| fig-height: 5
#| fig-width: 9
#| warning: false
#| message: false

# Eulerr Plot
fill <- c("#3B4992FF","#EE0000FF","#008B45FF","#631879FF","#008280FF","#BB0021FF",
          "#5F559BFF","#A20056FF")
p <- as.ggplot(
  plot(euler_set,
    labels = list(col = rep("white", length(genes))),
    fills = list(fill = fill),
    quantities = list(type = c("percent", "counts"),
    col = rep("white", length(genes))),
    main = "Eulerr")
)

p
```

