---
title: "比例韦恩图"
author:
  - "**[编辑]** [郑虎](https://github.com/ZhengTiger);"
---

::: callout-note
**Hiplot 网站**

本页面为 Hiplot `Eulerr Plot` 插件的源码版本教程，您也可以使用 Hiplot 网站实现无代码绘图，更多信息请查看以下链接:

<https://hiplot.cn/basic/eulerr?lang=zh_cn>
:::

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `eulerr`; `ggplotify`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("eulerr", quietly = TRUE)) {
  install.packages("eulerr")
}
if (!requireNamespace("ggplotify", quietly = TRUE)) {
  install.packages("ggplotify")
}

# 加载包
library(eulerr)
library(ggplotify)
```

```{r}
sessioninfo::session_info("attached")
```

## 数据准备

```{r load data, message=FALSE, warning=FALSE}
# 基因集重叠数据（自包含示例）
genes <- c(
  "LUAD" = 1000, "BRCA" = 1200, "COAD" = 800,
  "LUAD&BRCA" = 200, "LUAD&COAD" = 150, "BRCA&COAD" = 180,
  "LUAD&BRCA&COAD" = 80
)
euler_set <- euler(genes)

# 查看数据
print(genes)
```

## 可视化

```{r}
#| label: fig-1Eulerr
#| fig-cap: "比例韦恩图"
#| out.width: "95%"
#| fig-height: 5
#| fig-width: 9
#| warning: false
#| message: false

# 比例韦恩图
fill_colors <- c("#3B4992FF", "#EE0000FF", "#008B45FF", "#631879FF",
                 "#008280FF", "#BB0021FF", "#5F559BFF", "#A20056FF")
n_sets <- length(euler_set$sets)
n_subsets <- length(euler_set$original.values)
p <- as.ggplot(
  plot(euler_set,
    labels = list(col = rep("white", n_sets)),
    fills = list(fill = rep_len(fill_colors, n_sets)),
    quantities = list(type = c("percent", "counts"),
    col = rep("white", n_subsets)),
    main = "Eulerr")
)

p
```

