---
title: "Extended Scatter"
author:
  - "**[Editor]** Hu Zheng;"
  - "**[Contributors]** "
---

An extended scatter plot adds marginal plots to the basic scatter plot to provide a more comprehensive view of the data distribution.

## Setup

-   System Requirements: Cross-platform (Linux/MacOS/Windows)

-   Programming language: R

-   Dependent packages: `ggplot2`; `ggExtra`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# Install packages
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}
if (!requireNamespace("ggExtra", quietly = TRUE)) {
  install.packages("ggExtra")
}

# Load packages
library(ggplot2)
library(ggExtra)
```

## Data Preparation

```{r load data, message=FALSE, warning=FALSE}
# Load data
data <- read.delim("files/Hiplot/052-extended-scatter-data.txt", header = T)

# View data
head(data)
```

## Visualization

```{r fig-1Eulerr}
#| label: fig-1Eulerr
#| fig-cap: "Extended Scatter"
#| out.width: "95%"
#| fig-height: 4
#| fig-width: 6
#| warning: false
#| message: false

# Extended Scatter
p <- ggplot(data, aes(x = wt, y = mpg, color = cyl, size = cyl)) +
  geom_point() +
  geom_rug(alpha = 0.2, size = 1.5, col = "#4f80b3") +
  theme(legend.position = "none")

p <- ggMarginal(
  p, type = "densigram", fill = "#7054cc", color = "#7f0080",
  size = 4, bins = 30)

p
```


