---
title: "扇形图"
author:
  - "**[编辑]** 郑虎;"
  - "**[审核]** ."
---

扇形图是旨在以所占扇形的大小清楚表示各组数据所占百分比的统计图表。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `plotrix`; `ggplotify`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("plotrix", quietly = TRUE)) {
  install.packages("plotrix")
}
if (!requireNamespace("ggplotify", quietly = TRUE)) {
  install.packages("ggplotify")
}

# 加载包
library(plotrix)
library(ggplotify)
```

## 数据准备

载入数据为不同分组及其数据。

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- read.delim("files/Hiplot/054-fan-data.txt", header = T)

# 查看数据
head(data)
```

## 可视化

```{r fig-1Fan}
#| label: fig-1Fan
#| fig-cap: "Cox 模型森林图"
#| out.width: "95%"
#| fig-height: 4
#| fig-width: 6
#| warning: false
#| message: false

# Cox 模型森林图
p <- as.ggplot(function() {
  fan.plot(data[, 2], main = "", labels = as.character(data[, 1]),
           col = c("#E64B35FF","#4DBBD5FF","#00A087FF","#3C5488FF"))
  })

p
```

不同颜色表示不同组群 ，不同面积表示数据及占比。
