---
title: "Flower plot"
author:
  - "**[Editor]** Hu Zheng;"
  - "**[Contributors]** "
---

Flower plot with multiple sets.

## Setup

-   System Requirements: Cross-platform (Linux/MacOS/Windows)

-   Programming language: R

-   Dependent packages: `flowerplot`; `ggplotify`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# Install packages
if (!requireNamespace("flowerplot", quietly = TRUE)) {
  install_github("dongwei1220/flowerplot")
}
if (!requireNamespace("ggplotify", quietly = TRUE)) {
  install.packages("ggplotify")
}

# Load packages
library(flowerplot)
library(ggplotify)
```

## Data Preparation

```{r load data, message=FALSE, warning=FALSE}
# Load data
data <- read.delim("files/Hiplot/056-flowerplot-data.txt", header = T)

# View data
head(data)
```

## Visualization

```{r fig-1Flowerplot}
#| label: fig-1Flowerplot
#| fig-cap: "Flower plot"
#| out.width: "95%"
#| fig-height: 7
#| fig-width: 7
#| warning: false
#| message: false

# Flower plot
p <- as.ggplot(function(){
  flowerplot(
    flower_dat = data,
    angle = 90,
    a = 0.5,
    b = 2,
    r = 1,
    ellipse_col = "RdBu",
    circle_col = "#FFFFFF",
    label_text_cex = 1
  )})

p
```
