---
title: "Funnel Plot (metafor)"
author:
  - "**[Editor]** Hu Zheng;"
  - "**[Contributors]** "
---

Can be used to show potential bias factors in Meta-analysis.

## Setup

-   System Requirements: Cross-platform (Linux/MacOS/Windows)

-   Programming language: R

-   Dependent packages: `metafor`; `ggplotify`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# Install packages
if (!requireNamespace("metafor", quietly = TRUE)) {
  install.packages("metafor")
}
if (!requireNamespace("ggplotify", quietly = TRUE)) {
  install.packages("ggplotify")
}

# Load packages
library(metafor)
library(ggplotify)
```

## Data Preparation

```{r load data, message=FALSE, warning=FALSE}
# Load data
data <- read.delim("files/Hiplot/057-funnel-plot-metafor-data.txt", header = T)

# Convert data structure
data2 <- escalc(ri=ri, ni=ni, data = data, measure="ZCOR")
res <- rma(yi, vi, data = data2)

# View data
head(data2)
```

## Visualization

```{r fig-1Funnel-plot-metafor}
#| label: fig-1Funnel-plot-metafor
#| fig-cap: "Funnel Plot"
#| out.width: "95%"
#| fig-height: 5
#| fig-width: 8
#| warning: false
#| message: false

# Funnel Plot
p <- as.ggplot(function(){
  funnel(x = res, main = "Funnel Plot (metafor)",
         level = c(90, 95, 99), shade = c("white","#a90e07","#d23e0b"), refline = 0)
  })

p
```

