---
title: "漏斗图 (metafor)"
author:
  - "**[编辑]** 郑虎;"
  - "**[审核]** ."
---

可以用于分析 Meta 分析结果中潜在偏倚因子。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `metafor`; `ggplotify`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("metafor", quietly = TRUE)) {
  install.packages("metafor")
}
if (!requireNamespace("ggplotify", quietly = TRUE)) {
  install.packages("ggplotify")
}

# 加载包
library(metafor)
library(ggplotify)
```

## 数据准备

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- read.delim("files/Hiplot/057-funnel-plot-metafor-data.txt", header = T)

# 整理数据格式
data2 <- escalc(ri=ri, ni=ni, data = data, measure="ZCOR")
res <- rma(yi, vi, data = data2)

# 查看数据
head(data2)
```

## 可视化

```{r fig-1Funnel-plot-metafor}
#| label: fig-1Funnel-plot-metafor
#| fig-cap: "漏斗图"
#| out.width: "95%"
#| fig-height: 5
#| fig-width: 8
#| warning: false
#| message: false

# 漏斗图
p <- as.ggplot(function(){
  funnel(x = res, main = "Funnel Plot (metafor)",
         level = c(90, 95, 99), shade = c("white","#a90e07","#d23e0b"), refline = 0)
  })

p
```

