---
title: "Funnel Plot"
author:
  - "**[Editor]** Hu Zheng;"
  - "**[Contributors]** "
---

Can be used to show potential bias factors in Meta-analysis.

## Setup

-   System Requirements: Cross-platform (Linux/MacOS/Windows)

-   Programming language: R

-   Dependent packages: `FunnelPlotR`; `gridExtra`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# Install packages
if (!requireNamespace("FunnelPlotR", quietly = TRUE)) {
  install.packages("FunnelPlotR")
}
if (!requireNamespace("gridExtra", quietly = TRUE)) {
  install.packages("gridExtra")
}

# Load packages
library(FunnelPlotR)
library(gridExtra)
```

## Data Preparation

```{r load data, message=FALSE, warning=FALSE}
# Load data
data <- read.delim("files/Hiplot/058-funnel-plot-data.txt", header = T)

# View data
head(data)
```

## Visualization

```{r fig-1Funnel-plot-metafor}
#| label: fig-1Funnel-plot-metafor
#| fig-cap: "Funnel Plot"
#| out.width: "95%"
#| fig-height: 5
#| fig-width: 8
#| warning: false
#| message: false

# Funnel Plot
plot_cols <- c("#925E9FFF","#FDAF91FF","#AD002AFF","#ADB6B6FF","#00468BFF","#ED0000FF","#42B540FF","#0099B4FF")
p <- funnel_plot(
  data, numerator = los, denominator = prds,  group = provnum, data_type = "SR",
  limit = 99, label = "outlier", sr_method = "SHMI", trim_by=0.1, 
  title = "Funnel Plot", x_range = "auto", y_range = "auto",
  plot_cols=plot_cols
  )

p
```


