---
title: "饼状图（ggpiestats）"
author:
  - "**[编辑]** 郑虎;"
  - "**[审核]** ."
---

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `ggstatsplot`; `ggplot2`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("ggstatsplot", quietly = TRUE)) {
  install.packages("ggstatsplot")
}
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}

# 加载包
library(ggstatsplot)
library(ggplot2)
```

## 数据准备

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- read.delim("files/Hiplot/071-ggpiestats-data.txt", header = T)

# 整理数据格式
axis <- c("am", "cyl")
data[, axis[1]] <- factor(data[, axis[1]], levels = unique(data[, axis[1]]))
data[, axis[2]] <- factor(data[, axis[2]], levels = unique(data[, axis[2]]))

# 查看数据
head(data)
```

## 可视化

```{r fig-1ggpiestats}
#| label: fig-1ggpiestats
#| fig-cap: "饼状图"
#| out.width: "95%"
#| fig-height: 4
#| fig-width: 7
#| warning: false
#| error: false
#| message: false

# 饼状图
p <- ggpiestats(data = data, x = am, y = cyl,
                paired = F) +
  scale_fill_manual(values = c("#3B4992FF","#EE0000FF"))

p
```


