---
title: "GGPubr Boxplot"
author:
  - "**[Editor]** Hu Zheng;"
  - "**[Contributors]** "
---

Feature-rich boxplot (GGPubr interface).

## Setup

-   System Requirements: Cross-platform (Linux/MacOS/Windows)

-   Programming language: R

-   Dependent packages: `ggpubr`; `ggthemes`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# Install packages
if (!requireNamespace("ggpubr", quietly = TRUE)) {
  install.packages("ggpubr")
}
if (!requireNamespace("ggthemes", quietly = TRUE)) {
  install.packages("ggthemes")
}

# Load packages
library(ggpubr)
library(ggthemes)
```

## Data Preparation

```{r load data, message=FALSE, warning=FALSE}
# Load data
data <- read.delim("files/Hiplot/072-ggpubr-boxplot-data.txt", header = T)

# View data
head(data)
```

## Visualization

```{r fig-1ggpubr-boxplot}
#| label: fig-1ggpubr-boxplot
#| fig-cap: "GGPubr Boxplot"
#| out.width: "95%"
#| fig-height: 6
#| fig-width: 10
#| warning: false
#| error: false
#| message: false

# GGPubr Boxplot
p <- ggboxplot(
  data = data, x = "supp", y = "len", facet.by = "dose",
  merge = T,
  color = "supp",
  fill = "white") + 
  stat_compare_means(
    label = "p.signif",
    label.x.npc = "center",
    method = "wilcox") + 
  scale_y_continuous(expand = expansion(mult = c(0.2, 0.2))) +
  scale_fill_manual(values = c("#e04d39","#5bbad6")) +
  ggtitle("Complex Boxplot") + 
  theme_stata() +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12,hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 0, hjust = 0.5,vjust = 1),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))

p
```

