---
title: "序列 Logo"
author:
  - "**[编辑]** 郑虎;"
  - "**[审核]** ."
---

序列 Logo 是一种用来描述结合位点序列模式的图形。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `ggseqlogo`; `ggplot2`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("ggseqlogo", quietly = TRUE)) {
  install.packages("ggseqlogo")
}
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}

# 加载包
library(ggseqlogo)
library(ggplot2)
```

## 数据准备

载入数据为多个转录因子在多个基因上的结合位点的序列。

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- read.delim("files/Hiplot/074-ggseqlogo-data.txt", header = T)

# 整理数据格式
data <- data[, !sapply(data, function(x) {all(is.na(x))})]
data <- as.list(data)
data <- lapply(data, function(x) {return(x[!is.na(x)])})

# 查看数据
str(data)
```

## 可视化

```{r fig-1ggseqlogo}
#| label: fig-1ggseqlogo
#| fig-cap: "序列 Logo"
#| out.width: "95%"
#| fig-height: 6
#| fig-width: 8
#| warning: false
#| error: false
#| message: false

# 序列 Logo
p <- ggseqlogo(
  data,
  ncol = 4,
  col_scheme = "nucleotide",
  seq_type = "dna",
  method = "bits") + 
  theme(plot.title = element_text(hjust = 0.5))

p
```

采用 bits 计算的方式将一个结合位点序列展示在图表一列，可以清晰观测到不同序列占比较大的碱基。



