---
title: "Complex-Violin"
author:
  - "**[Editor]** Hu Zheng;"
  - "**[Contributors]** "
---

## Setup

-   System Requirements: Cross-platform (Linux/MacOS/Windows)

-   Programming language: R

-   Dependent packages: `ggstatsplot`; `ggplot2`; `cowplot`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# Install packages
if (!requireNamespace("ggstatsplot", quietly = TRUE)) {
  install.packages("ggstatsplot")
}
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}
if (!requireNamespace("cowplot", quietly = TRUE)) {
  install.packages("cowplot")
}

# Load packages
library(ggstatsplot)
library(ggplot2)
library(cowplot)
```

## Data Preparation

```{r load data, message=FALSE, warning=FALSE}
# Load data
data <- read.delim("files/Hiplot/075-ggwithinstats-data.txt", header = T)

# Convert data structure
axis <- c("condition", "desire", "region")
data[, axis[1]] <- factor(data[, axis[1]], levels = unique(data[, axis[1]]))
data[, axis[3]] <- factor(data[, axis[3]], levels = unique(data[, axis[3]]))

# View data
str(data)
```

## Visualization

```{r fig-1ggwithinstats}
#| label: fig-1ggwithinstats
#| fig-cap: "Complex-Violin"
#| out.width: "95%"
#| fig-height: 5
#| fig-width: 7
#| warning: false
#| error: false
#| message: false

# Complex-Violin
g <- unique(data[,axis[3]])
plist <- list()
for (i in 1:length(g)) {
  fil <- data[,axis[3]] == g[i]
  plist[[i]] <- ggwithinstats(
    data = data[fil,], x = condition, y = desire,
    title= paste('', axis[3], g[i], sep = ':'),
    p.adjust.method = "holm",
    plot.type = "boxviolin",
    pairwise.comparisons = T,
    pairwise.display = "significant",
    effsize.type = "unbiased",
    notch = T,
    type = "parametric",
    k = 2,
    plotgrid.args = list(ncol = 2)
  ) +
    scale_color_manual(values = c("#3B4992FF","#EE0000FF"))
}

plot_grid(plotlist = plist, ncol = 2)
```




