---
title: "GO气泡图"
author:
  - "**[编辑]** 郑虎;"
  - "**[审核]** ."
---

GO气泡图用于显示按z-score或adjusted p-value的负相对序列的Z-score彩色气泡图。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `GOplot`; `ggplotify`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("GOplot", quietly = TRUE)) {
  install.packages("GOplot")
}
if (!requireNamespace("ggplotify", quietly = TRUE)) {
  install.packages("ggplotify")
}

# 加载包
library(GOplot)
library(ggplotify)
```

## 数据准备

加载的数据是具有七个列的GO富集的结果：category, GO id, GO term, gene count, gene name, logFC, adjust pvalue and zscore。

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- read.delim("files/Hiplot/078-gobubble-data.txt", header = T)

# 整理数据格式
colnames(data) <- c("category","ID","term","count","genes","logFC","adj_pval","zscore")
data <- data[data$category %in% c("BP","CC","MF"),]
data <- data[!is.na(data$adj_pval),]
data$adj_pval <- as.numeric(data$adj_pval)
data$zscore <- as.numeric(data$zscore)

# 查看数据
head(data)
```

## 可视化

```{r fig-1gobubble}
#| label: fig-1gobubble
#| fig-cap: "GO气泡图"
#| out.width: "95%"
#| fig-height: 14
#| fig-width: 12
#| warning: false
#| error: false
#| message: false

# GO气泡图
p <- function () {
  GOBubble(data, display = "single", title = "GO Enrichment Bubbleplot",
           colour = c("#FC8D59","#FFFFBF","#99D594"),
           labels = 0,  ID = T, table.legend = T, table.col = T, bg.col = F) + 
  theme(plot.title = element_text(hjust = 0.5))
}
p <- as.ggplot(p)

p
```

如示例图所示，图的x轴表示z-score。y轴上显示了 adjusted p-value 的负对数（对应于该 term 的重要性）。绘制圆圈的面积与分配给该 term 的基因数量成正比。每个圆都根据其类别进行着色，并用 ID 或 term 名称标记。


