---
title: "Group Rank Dotplot"
author:
  - "**[Editor]** Hu Zheng;"
  - "**[Contributors]** "
---

Values distribution for different groups.

## Setup

-   System Requirements: Cross-platform (Linux/MacOS/Windows)

-   Programming language: R

-   Dependent packages: `sigminer`; `ggplot2`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# Install packages
if (!requireNamespace("sigminer", quietly = TRUE)) {
  install_github("ShixiangWang/sigminer")
}
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}

# Load packages
library(sigminer)
library(ggplot2)
```

## Data Preparation

```{r load data, message=FALSE, warning=FALSE}
# Load data
data <- read.delim("files/Hiplot/080-grdotplot-data.txt", header = T)

# View data
head(data)
```

## Visualization

```{r fig-1grdotplot}
#| label: fig-1grdotplot
#| fig-cap: "Group Rank Dotplot"
#| out.width: "95%"
#| fig-height: 4
#| fig-width: 6
#| warning: false
#| error: false
#| message: false

# Group Rank Dotplot
p <- show_group_distribution(data, gvar = "gvar",  dvar = "dvar", 
                             order_by_fun = F)

p
```



