---
title: "分组哑铃图"
author:
  - "**[编辑]** 郑虎;"
  - "**[审核]** ."
---

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `ggplot2`; `ggalt`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}
if (!requireNamespace("ggalt", quietly = TRUE)) {
  install.packages("ggalt")
}

# 加载包
library(ggplot2)
library(ggalt)
```

## 数据准备

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- read.delim("files/Hiplot/083-group-dumbbell-data.txt", header = T)

# 整理数据格式
data <- data[order(data[["group"]], data[["y1952"]]),]
data[["country"]] <- factor(data[["country"]], levels = data[["country"]])

# 查看数据
head(data)
```

## 可视化

```{r fig-1group-dumbbell}
#| label: fig-1group-dumbbell
#| fig-cap: "分组哑铃图"
#| out.width: "95%"
#| fig-height: 4
#| fig-width: 6
#| warning: false
#| error: false
#| message: false

# 分组哑铃图
p <- ggplot(data = data, aes(x = y1952, xend = y2007, y = country, color = group)) +
  geom_dumbbell(size = 1, size_xend = 2, size_x = 2) +
  theme_bw()

p
```


