---
title: "直方图"
author:
  - "**[编辑]** 郑虎;"
  - "**[审核]** ."
---

直方图是由一系列高度不等的纵向条纹或线段表示连续性变量数据的分布情况。

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `ggplot2`; `ggthemes`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}
if (!requireNamespace("ggthemes", quietly = TRUE)) {
  install.packages("ggthemes")
}

# 加载包
library(ggplot2)
library(ggthemes)
```

## 数据准备

载入数据为数据集(不同治疗方案治疗效果数据)。

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- read.delim("files/Hiplot/088-histogram-data.txt", header = T)

# 整理数据格式
data[, 2] <- factor(data[, 2], levels = unique(data[, 2]))

# 查看数据
head(data)
```

## 可视化

```{r fig-1histogram}
#| label: fig-1histogram
#| fig-cap: "直方图"
#| out.width: "95%"
#| fig-height: 7
#| fig-width: 10
#| warning: false
#| error: false
#| message: false

# 直方图
p <- ggplot(data, aes(x=Value, fill=Group2)) +
  geom_histogram(alpha = 1, bins = 12, col = "white") +
  ggtitle("Histogram Plot") +
  scale_fill_manual(values = c("#e04d39","#5bbad6","#1e9f86")) +
  theme_stata() +
  theme(text = element_text(family = "Arial"),
        plot.title = element_text(size = 12,hjust = 0.5),
        axis.title = element_text(size = 12),
        axis.text = element_text(size = 10),
        axis.text.x = element_text(angle = 0, hjust = 0.5,vjust = 1),
        legend.position = "right",
        legend.direction = "vertical",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10))

p
```

图中长方形的宽度与组距成正比且可不相同，纵轴代表频数。

