---
title: "区间条形图"
author:
  - "**[编辑]** 郑虎;"
  - "**[审核]** ."
---

## 环境配置

-   系统: Cross-platform (Linux/MacOS/Windows)

-   编程语言: R

-   依赖包: `ggplot2`

```{r packages setup, message=FALSE, warning=FALSE, output=FALSE}
# 安装包
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}

# 加载包
library(ggplot2)
```

## 数据准备

案例数据为一年十二个月份的最高和最低温度和对应的月份简称。通过案例数据绘制了每个月份的温度区间及温度均线。

```{r load data, message=FALSE, warning=FALSE}
# 加载数据
data <- read.delim("files/Hiplot/090-interval-bar-chart-data.txt", header = T)

# 整理数据格式
data$name_num <- match(data[["month"]], unique(data[["month"]]))

# 查看数据
head(data)
```

## 可视化

```{r fig-1interval-bar-chart}
#| label: fig-1interval-bar-chart
#| fig-cap: "区间条形图"
#| out.width: "95%"
#| fig-height: 4
#| fig-width: 7
#| warning: false
#| error: false
#| message: false

# 区间条形图
p <- ggplot(data, aes(x = month, y = max_temperature)) +
  geom_rect(aes(xmin = name_num - 0.4, xmax = name_num + 0.4,
                ymin = min_temperature, ymax = max_temperature), 
            fill = "#282726", alpha = 0.7) +
  geom_line(aes(x = name_num, y = mean), color = "#006064", size = 0.8) +
  labs(x = "Month", y = "Temperature") +
  scale_x_discrete() +
  theme_bw()

p
```



